# fly.toml app configuration file generated for pocketbase-docker-zkhfiq on 2025-02-19T10:47:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocketbase-docker-zkhfiq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
